### ISSUE TITLE
Invalid SemVer format

### ISSUE THREAD

**Issue by o3o** [symmetryinvestments/dubproxy#3]
I've created a simply library [mylib](https://github.com/o3o/mylib.git) with two tags
```
$ cd mylib
$ git tag
v0.1.0
v2.0.0
```

and a dubproxy file:
```
$ cat dubproxy.json 
{
	"packages" : {
		"mylib" : "https://github.com/o3o/mylib.git"
	}
}
```

Then:
```
$ dubproxy -g mylib
```
creates 

```
/home/o3o/.dub/packages/mylib-0.1.0
/home/o3o/.dub/packages/mylib-2.0.0
/home/o3o/.dub/packages/mylib-HEAD
/home/o3o/.dub/packages/mylib-master
```

Well, I try to use mylib in myclient:
```
$ cd myclient
$ cat dub.sdl 

name "myclient"
dependency "mylib" version="~>0.1.0"
```
when I build:

```
$ dub build
Invalid SemVer format: HEAD
```
So, I remove `/home/o3o/.dub/packages/mylib-HEAD`
```
$ rm -fr ~/.dub/packages/mylib-HEAD
$ dub build
Invalid SemVer format: master
```

Finally if I remove `/home/o3o/.dub/packages/mylib-master` it works:
```
$ rm -fr ~/.dub/packages/mylib-master/
$ dub build
Performing "debug" build using dmd for x86_64.
mylib 0.1.0: building configuration "library"...
myclient ~master: building configuration "application"...
Linking...
```

Where am I wrong?

Thank you very much

**Comment by burner** [comment]
I don't think you are wrong. I think I need to have another look how depending on ~master works with dub. You can however use 
```sh
dubproxy -g mylib:v2.0.0 
```
to get **only** a specific version

**Comment by o3o** [comment]
Thank you.
And thank you for dubproxy....I think it's one of the most useful tools of the last year

**Comment by burner** [comment]
thank you, glad to hear

**Comment by burner** [comment]
please check dubproxy v1.0.2

I think that version should fix this bug.

**Comment by o3o** [comment]
It works like a charm! thanks
